#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: WaurimaL

# Short bio or description (displayed in the header)
description: Educator

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://www.artofit.org/image-gallery/611856299355449087/%EC%84%A0%EC%83%9D%EB%8B%98-%EC%9D%BC%EB%9F%AC%EC%8A%A4%ED%8A%B8-ai-%EB%AC%B4%EB%A3%8C%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C-free-teacher-image-vector-%EC%9D%B4%EB%AF%B8%EC%A7%80-%EC%82%AC%EC%9A%A9%EC%95%BD%EA%B4%80-%ED%99%95%EC%9D%B8-%EB%B0%8F-%EC%86%8C%EC%8A%A4-%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C%EB%8A%94-%EC%96%B4%EB%B0%98%EB%B8%8C%EB%9F%AC%EC%8B%9C-%ED%99%88%ED%8E%98%EC%9D%B4%EC%A7%80%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%98%EC%84%B8%EC%9A%94-%EC%96%B4%EB%B0%98%EB%B8%8C%EB%9F%AC%EC%8B%9C-%EB%AC%B4%EB%A3%8C%EC%9D%BC%EB%9F%AC%EC%8A%A4%ED%8A%B8-%EC%9D%BC%EB%9F%AC%EC%8A%A4%ED%8A%B8%EB%A0%88%EC%9D%B4%EC%85%98-%EB%94%94%EC%9E%90%EC%9D%B4%EB%84%88%ED%83%80%EB%AF%B8-%EC%9D%B4%EB%AF%B8%EC%A7%80%EC%86%8C%EC%8A%A4-%EC%9D%BC%EB%9F%AC%EC%8A%A4%ED%8A%B8%EC%95%84%EC%9D%B4%EB%94%94%EC%96%B4-%ED%8C%A8%ED%84%B4-%EC%9D%B4%EB%AF%B8%EC%A7%80-%EC%9D%BC%EB%9F%AC%EC%8A%A4%ED%8A%B8%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C-urbanbrush-%EB%AC%B4%EB%A3%8C%EC%9D%BC%EB%9F%AC%EC%8A%A4%ED%8A%B8%EC%82%AC%EC%9D%B4%ED%8A%B8-%EA%B7%B8%EB%9E%98%ED%94%BD%EB%94%94%EC%9E%90%EC%9D%B8-ai-download-illustration-%EB%B0%B1%ED%84%B0%EC%9D%B4%EB%AF%B8%EC%A7%80-%EB%B2%A1%ED%84%B0%EC%9D%B4%EB%AF%B8%EC%A7%80-vector-%ED%8C%9D%EC%97%85-%ED%85%9C%ED%94%8C%EB%A6%BF-%ED%99%88%ED%8E%98%EC%9D%B4%EC%A7%80-%EB%AC%B4%EB%A3%8C%EC%9D%B4%EB%AF%B8%EC%A7%80-%EB%AC%B4%EB%A3%8C%EC%9D%BC%EB%9F%AC%EC%8A%A4%ED%8A%B8-%EB%AC%B4%EB%A3%8C%EB%B0%B1%ED%84%B0-%EA%B7%B8%EB%9E%98%ED%94%BD%EC%9D%B4%EB%AF%B8%EC%A7%80-%EB%B2%A1%ED%84%B0-%ED%95%A9%EC%84%B1%EC%82%AC%EC%A7%84-%EC%95%84%EC%9D%B4%EC%BD%98-%ED%94%BD%ED%86%A0%EA%B7%B8%EB%9E%A8-%EC%9D%BC%EB%9F%AC%EC%8A%A4%ED%8A%B8-%EB%B0%B0%EB%84%88-%EC%82%AC%EC%A7%84-%ED%8F%AC%ED%86%A0%EA%B7%B8%EB%9E%98%ED%94%BC-%ED%8F%AC%ED%86%A0%EA%B7%B8%EB%9E%98%ED%8D%BC-%EB%94%94%EC%9E%90%EC%9D%B4%EB%84%88-%EB%B0%B1%EA%B7%B8%EB%9D%BC%EC%9A%B4%EB%93%9C-%EC%9B%B9%ED%85%9C%ED%94%8C%EB%A6%BF-ppt%EB%94%94%EC%9E%90%EC%9D%B8-%ED%8F%AC%EC%8A%A4%ED%84%B0-%EC%9B%B9%EB%94%94%EC%9E%90%EC%9D%B8-tommy/

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: waurimal@snuecse.org
  facebook:
  flickr:
  github: waurimal.github.io
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: jekyllrb
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://waurimal.dothome.co.kr

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
